

/*
create user Sklep identified by golden123;
grant all privileges to Sklep; - TWORZENIE NOWEGO UZYTKOWNIKA ORAZ NADAWANIE UPRAWNIEÑ

SELECT * FROM hr.countries - gdy tabela znajduje sie w other user hr
*/
CREATE TABLE PRACOWNICY
(
ID NUMBER, 
IMIE VARCHAR2(30), 
NAZWISKO VARCHAR2(60), 
PESEL NUMBER, 
PLEC VARCHAR2(1), 
DATA_URODZENIA DATE, 
PENSJA NUMBER
);

CREATE TABLE PRODUKTY 
(
ID_PRODUKTY NUMBER,
NAZWA_PRODUKTU VARCHAR2(100),
TYP_PRODUKTU VARCHAR2(30),
CENA_SPRZEDAZY NUMBER,
CENA_ZAKUPU NUMBER,
STAWKA_PODATKU NUMBER
);

CREATE TABLE DEPARTAMENTY 
(
KOD_DEPARTAMENTU NUMBER,
NAZWA_DEPARTAMENTU VARCHAR2(50),
ID_KIEROWNIKA NUMBER,
MIEJSCOWOŒÆ VARCHAR2(80)
);

INSERT INTO PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA)
VALUES (7, 'Stefan', 'Siarzewski', 65161513345, 'M', '65/07/12', 7000);

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/
/* CONSTRAINY */

INSERT INTO PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA)
VALUES (11, 'JSFA', null, 12121212121, 'M', '70/05/08', 1000);

ALTER TABLE PRACOWNICY
MODIFY IMIE NOT NULL;
ALTER TABLE PRACOWNICY
MODIFY NAZWISKO NOT NULL;

ALTER TABLE PRACOWNICY
MODIFY PESEL NOT NULL;  /* DODANE CONSTRAINY NIE MOZNA POZOSTAWIC POLA PUSTEGO */


INSERT INTO PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA)
VALUES (11, 'JSFA', 'ANS', 12121212121, NULL, '70/05/08', 1000);

ALTER TABLE PRACOWNICY
MODIFY PLEC CHECK (PLEC IN ('M','K')); /* NIE MOZNA DODAC INNEJ WARTOSCI NIZ M I K DUZYMI LITERAMI */

ALTER TABLE PRACOWNICY
MODIFY PLEC NOT NULL;

ALTER TABLE PRACOWNICY
MODIFY PESEL NUMBER(11) NOT NULL;

INSERT INTO PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA)
VALUES (11, 'JSFA', 'ANS', 12345678901234, 'M', '70/05/08', 1000);

            Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('1','Jan','Kowalski','88020512345','M',to_date('88/02/05','RR/MM/DD'),'4000');
            Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('2','Krzysztof','Kapusta','70122012345','M',to_date('70/12/20','RR/MM/DD'),'2500');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('3','Magdalena','Dzwonkowska','92081612345','K',to_date('92/08/16','RR/MM/DD'),'5000');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('4','Karol','Krawczyk','82010112345','M',to_date('82/01/01','RR/MM/DD'),'3000');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('5','Joanna','Bak','90121212345','K',to_date('90/12/12','RR/MM/DD'),'2700');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('6','Robert','Psikuta','95070815642','M',to_date('95/07/08','RR/MM/DD'),'4200');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('7','Stefan','Siarzewski','60051274391','M',to_date('60/05/12','RR/MM/DD'),'4550');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('8','Zofia','Brzydal','84021659712','K',to_date('84/02/16','RR/MM/DD'),'2400');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('9','Julia','Niedziela','81050242315','K',to_date('81/05/02','RR/MM/DD'),'7000');
			Insert into PRACOWNICY (ID_PRACOWNICY,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,PENSJA) values ('10','Bartosz','Karmel','58031245679','M',to_date('58/03/12','RR/MM/DD'),'5120');
            
INSERT INTO PRACOWNICY (ID_PRACOWNICY, IMIE, NAZWISKO, PLEC, DATA_URODZENIA, PENSJA, PESEL) VALUES ('11', 'Dariusz', 'Maciag', 'M', '88/09/06', '5300', '88090613547');
INSERT INTO PRACOWNICY (ID_PRACOWNICY, IMIE, NAZWISKO, PLEC, DATA_URODZENIA, PENSJA, PESEL) VALUES ('12', 'Mariusz', 'Maciag', 'M', '86/05/05', '5300', '86050513347');
INSERT INTO PRACOWNICY (ID_PRACOWNICY, IMIE, NAZWISKO, PLEC, DATA_URODZENIA, PENSJA, PESEL) VALUES ('13', 'Niko', 'Tymkiewicz', 'M', '83/02/02', '6100', '83020214347');
INSERT INTO PRACOWNICY (ID_PRACOWNICY, IMIE, NAZWISKO, PLEC, DATA_URODZENIA, PENSJA, PESEL) VALUES ('14', 'Marko', 'Szymkiewicz', 'M', '82/03/03', '4100', '82030314347');

SELECT * FROM PRACOWNICY;

INSERT INTO PRACOWNICY (ID_PRACOWNICY, IMIE, NAZWISKO, PLEC, DATA_URODZENIA, PENSJA, PESEL) VALUES ('14', 'Mariusz', 'Jarzyna', 'M', '82/03/03', '4100', '82030314347');
INSERT INTO PRACOWNICY (ID_PRACOWNICY, IMIE, NAZWISKO, PLEC, DATA_URODZENIA, PENSJA, PESEL) VALUES (null, 'Mariusz', 'Jarzyna', 'M', '82/03/03', '4100', '82030314347');

/* KLUCZE */
ALTER TABLE PRACOWNICY
ADD CONSTRAINT PRACOWNICY_PK PRIMARY KEY(ID_PRACOWNICY);

ALTER TABLE PRODUKTY
ADD CONSTRAINT PRODUKTY_PK PRIMARY KEY(ID_PRODUKTY);

ALTER TABLE DEPARTAMENTY
ADD CONSTRAINT DEPARTAMENTY_PK PRIMARY KEY(KOD_DEPARTAMENTU);

INSERT INTO PRODUKTY (ID_PRODUKTY, NAZWA_PRODUKTU, TYP_PRODUKTU, CENA_SPRZEDAZY, CENA_ZAKUPU, STAWKA_PODATKU) VALUES ('1', 'Baton "Mars"', 'S³odycz', '2,5', '1,5', '23');
INSERT INTO PRODUKTY (ID_PRODUKTY, NAZWA_PRODUKTU, TYP_PRODUKTU, CENA_SPRZEDAZY, CENA_ZAKUPU, STAWKA_PODATKU) VALUES ('2', 'Chleb', 'Pieczywo', '3', '1,2', '23');

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/
Select IMIE, NAZWISKO from PRACOWNICY;

SELECT IMIE AS NAME FROM PRACOWNICY;

SELECT * FROM DEPARTAMENTY;

UPDATE DEPARTAMENTY
SET ID_KIEROWNIKA=5
WHERE KOD_DEPARTAMENTU=5;

SELECT * FROM DEPARTAMENTY;

ALTER TABLE DEPARTAMENTY
ADD CONSTRAINT FK_DEP_PRACOWNIK FOREIGN KEY(ID_KIEROWNIKA)
REFERENCES PRACOWNICY(ID_PRACOWNICY); /* ZMIEN TABELE DEPARTAMENTY DODAJ KLUCZ OBCY O NAZWIE FK_DEP_PRACONIK DO KOLUMNY ID KIEROWNIKA ODNOSZACY SIE DO KOLUMNY ID W TABELI PRACOWNICY */


SELECT * FROM PRACOWNICY;

INSERT INTO PRACOWNICY (ID_PRACOWNICY, IMIE, NAZWISKO, PLEC, DATA_URODZENIA, PENSJA, PESEL) VALUES (15, 'Sebastian', 'Krawczyk', 'M', '88/03/12', 7000, 88031258123);

SELECT KOD_DEPARTAMENTU, NAZWA_DEPARTAMENTU
FROM DEPARTAMENTY;

DELETE FROM PRACOWNICY
WHERE ID_PRACOWNICY = 15;

SELECT KOD_DEPARTAMENTU, ID_KIEROWNIKA, NAZWA_DEPARTAMENTU FROM DEPARTAMENTY;

ALTER TABLE DEPARTAMENTY
MODIFY ID_KIEROWNIKA NOT NULL;
/* ------------------------------------------------------------------------------------------------------------------------------------------------*/

/* TWORZENIE TABELI Z CONSTRAINEM */
CREATE TABLE TYPY_PRODUKTÓW
(
TYP_PRODUKTU VARCHAR2(20) PRIMARY KEY,
NAZWA_PE£NA VARCHAR2(40) NOT NULL,
RABAT NUMBER,
OKRES_WA¯NOŒCI VARCHAR2(1) CHECK (OKRES_WA¯NOŒCI IN ('K', 'D'))
);

UPDATE PRODUKTY
SET TYP_PRODUKTU = 'ALK'
WHERE TYP_PRODUKTU = 'Alkohol';

INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('SLO', 'S³odycz', null, 'K');
INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('PIE', 'Pieczywo', null, 'K');
INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('NAS', 'Nasiona', null, 'D');
INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('NAB', 'Nabia³', null, 'K');
INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('KOS', 'Kosmetyki', null, 'D');
INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('NAP', 'Napoje', null, 'D');
INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('ALK', 'Alkohol', null, 'D');

ALTER TABLE PRODUKTY
ADD CONSTRAINT FK_TYP_PRODUKTU FOREIGN KEY(TYP_PRODUKTU)
REFERENCES TYPY_PRODUKTÓW(TYP_PRODUKTU);


INSERT INTO TYPY_PRODUKTÓW (TYP_PRODUKTU, NAZWA_PE£NA, RABAT, OKRES_WA¯NOŒCI) VALUES ('WAR', 'Warzywo', null, 'K');

SELECT * FROM PRODUKTY;
INSERT INTO PRODUKTY (ID_PRODUKTY, NAZWA_PRODUKTU, TYP_PRODUKTU, CENA_SPRZEDAZY, CENA_ZAKUPU, STAWKA_PODATKU) VALUES ('21', 'Jab³ko', 'OWO', 4, 2.52, 23);
INSERT INTO PRODUKTY (ID_PRODUKTY, NAZWA_PRODUKTU, TYP_PRODUKTU, CENA_SPRZEDAZY, CENA_ZAKUPU, STAWKA_PODATKU) VALUES ('22', 'Pomarañcza', 'OWO', 8, 5.01, 23);
INSERT INTO PRODUKTY (ID_PRODUKTY, NAZWA_PRODUKTU, TYP_PRODUKTU, CENA_SPRZEDAZY, CENA_ZAKUPU, STAWKA_PODATKU) VALUES ('23', 'Banan', 'OWO', 7.25, 4.99, 23);
INSERT INTO PRODUKTY (ID_PRODUKTY, NAZWA_PRODUKTU, TYP_PRODUKTU, CENA_SPRZEDAZY, CENA_ZAKUPU, STAWKA_PODATKU) VALUES ('24', 'Pomidor malinowy', 'WAR', 12.99, 10.99, 23);
INSERT INTO PRODUKTY (ID_PRODUKTY, NAZWA_PRODUKTU, TYP_PRODUKTU, CENA_SPRZEDAZY, CENA_ZAKUPU, STAWKA_PODATKU) VALUES ('25', 'Ogórek', 'WAR', 2.99, 1.99, 23);

ALTER TABLE PRODUKTY
ADD JEDNOSTKA VARCHAR2(10);

UPDATE PRODUKTY
SET JEDNOSTKA = 'kg'
WHERE ID_PRODUKTY > 20;

/* £¥CZENIE TABEL DO WYŒWIETLENIA */
SELECT * FROM PRODUKTY
INNER JOIN TYPY_PRODUKTÓW
ON PRODUKTY.TYP_PRODUKTU = TYPY_PRODUKTÓW.TYP_PRODUKTU;

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/

/* PRZYGOTOWANIE DANYCH I EXPORT DO EXELA - Prawy na tabele EXPORT format excel */

SELECT NAZWA_PRODUKTU, CENA_ZAKUPU, 
CEIL(CENA_SPRZEDAZY*(1+STAWKA_PODATKU/100)*100)/100 AS SPRZEDA¯, STAWKA_PODATKU, /* CEIL ZAOKRAGLENIE DO GORY, FLOOR - DO DOLU */
CEIL(CENA_SPRZEDAZY*(1+STAWKA_PODATKU/100)*100)/100 - CENA_ZAKUPU AS MAR¯A
FROM PRODUKTY;

SELECT NAZWA_PRODUKTU,CENA_ZAKUPU,
CENA_SPRZEDAZY AS SPRZEDA¯, STAWKA_PODATKU,
CENA_SPRZEDAZY - CENA_ZAKUPU AS MAR¯A
FROM PRODUKTY;

/* IMPORT danych do bazy - TWORZYMY NOWA TABELE Z DANYMI TAKIMI JAK W EXCELU NASTEPNIE KLIKAMY J¥ IMPORT DATA */

CREATE TABLE DOSTAWCY (
ID_DOSTAWCY NUMBER PRIMARY KEY,
NAZWA_DOSTAWCY VARCHAR2(50) NOT NULL,
KOD_RODZAJU_ŒRODKA_TRANSPORTU VARCHAR2(10),
STATUS_AKTYWNOŒCI VARCHAR2(1)
);

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/

/* INTRUKCJA GROUP BY - GRUPOWANIE DANYCH */

SELECT AVG(CENA_ZAKUPU) FROM PRODUKTY;
SELECT KOD_RODZAJU_ŒRODKA_TRANSPORTU, COUNT(*) FROM DOSTAWCY
GROUP BY KOD_RODZAJU_ŒRODKA_TRANSPORTU;

SELECT PLEC,SUM(PENSJA)
FROM PRACOWNICY
GROUP BY PLEC;

SELECT TYP_PRODUKTU, SUM(CENA_SPRZEDAZY) AS SUMA_SPRZEDA¯Y, ROUND(AVG(CENA_SPRZEDAZY),2) AS ŒREDNIA
FROM PRODUKTY
GROUP BY TYP_PRODUKTU;

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/
/* INTRUKCJA WHERE SK£ADNIA WHERE + ARGUMENT + OPERATOR + ARGUMENT NP: WHERE NAZWA = 'Michal' */

UPDATE PRODUKTY 
SET STAWKA_PODATKU = 16
WHERE TYP_PRODUKTU = 'OWO';

SELECT * FROM PRACOWNICY
WHERE PENSJA < 3500;

DELETE FROM DOSTAWCY
WHERE KOD_RODZAJU_ŒRODKA_TRANSPORTU IN ('TIR', 'BUS');

DELETE FROM DOSTAWCY
WHERE KOD_RODZAJU_ŒRODKA_TRANSPORTU NOT IN ('AUT', 'VAN');

SELECT * FROM PRACOWNICY
WHERE PENSJA > 4000 AND ID_PRACOWNICY < 7;

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/
/* SORTOWANIE // ORDER BY */

SELECT * FROM TYPY_PRODUKTÓW
ORDER BY OKRES_WA¯NOŒCI;

SELECT * FROM TYPY_PRODUKTÓW
ORDER BY OKRES_WA¯NOŒCI ASC;

SELECT * FROM TYPY_PRODUKTÓW
ORDER BY OKRES_WA¯NOŒCI DESC;

SELECT * FROM (
SELECT * FROM PRACOWNICY
ORDER BY DATA_URODZENIA ASC
)
WHERE ROWNUM <= 5;

SELECT * FROM (
SELECT * FROM PRACOWNICY 
ORDER BY IMIE ASC
)
WHERE PLEC = 'M';

SELECT * FROM (
SELECT * FROM PRACOWNICY 
ORDER BY ID_PRACOWNICY DESC
)
WHERE PLEC = 'M';

SELECT * FROM PRACOWNICY
WHERE PLEC = 'M'
ORDER BY IMIE;

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/
/* INTRUKCJA JOIN FROM NAZWA_TABELI JOIN NAZWA_TABELI2 ON NAZWA_TABELI.KOLUMNA = NAZWA_TABELI2.KOLUMNA */

SELECT NAZWA_DEPARTAMENTU, ID_PRACOWNICY, ID_KIEROWNIKA, IMIE, NAZWISKO FROM DEPARTAMENTY
JOIN PRACOWNICY ON DEPARTAMENTY.ID_KIEROWNIKA = PRACOWNICY.ID_PRACOWNICY;


SELECT NAZWA_PRODUKTU, OKRES_WA¯NOŒCI, PRODUKTY.TYP_PRODUKTU FROM PRODUKTY
JOIN TYPY_PRODUKTÓW ON PRODUKTY.TYP_PRODUKTU = TYPY_PRODUKTÓW.TYP_PRODUKTU;

/* ------------------------------------------------------------------------------------------------------------------------------------------------*/

SELECT TYP_PRODUKTU FROM PRODUKTY
WHERE CENA_SPRZEDAZY >= 8 AND CENA_SPRZEDAZY <= 18;

SELECT TYP_PRODUKTU FROM PRODUKTY
WHERE CENA_SPRZEDAZY BETWEEN 8 AND 18;

SELECT NAZWA_PE£NA FROM TYPY_PRODUKTÓW
WHERE TYP_PRODUKTU IN ('OWO', 'WAR', 'KOS');

/* TWORZENIE PODZAPYTAÑ */

/*SELECT TYP_PRODUKTU FROM PRODUKTY
WHERE CENA_SPRZEDAZY BETWEEN 8 AND 18; */

SELECT NAZWA_PE£NA FROM TYPY_PRODUKTÓW
WHERE TYP_PRODUKTU IN (SELECT TYP_PRODUKTU
                        FROM PRODUKTY
                        WHERE CENA_SPRZEDAZY BETWEEN 8 AND 18);
                        
/*SELECT PENSJA FROM PRACOWNICY
WHERE ID_PRACOWNICY = 10; 
SELECT IMIE, NAZWISKO, PENSJA
FROM PRACOWNICY
WHERE PENSJA > 5120; */

SELECT IMIE, NAZWISKO, PENSJA
FROM PRACOWNICY
WHERE PENSJA > (SELECT PENSJA FROM PRACOWNICY WHERE ID_PRACOWNICY = 10);


/*SELECT ROUND(AVG(PENSJA), 2) FROM PRACOWNICY;
SELECT IMIE, NAZWISKO, PENSJA, AVG(PENSJA)
FROM PRACOWNICY
GROUP BY IMIE, NAZWISKO, PENSJA; */

SELECT IMIE, NAZWISKO, PENSJA, (SELECT ROUND(AVG(PENSJA), 2) FROM PRACOWNICY)
FROM PRACOWNICY;

SELECT * FROM (SELECT * FROM PRACOWNICY 
              ORDER BY DATA_URODZENIA)
WHERE ROWNUM <=5;

/*SELECT STAWKA_PODATKU FROM PRODUKTY
WHERE NAZWA_PRODUKTU = 'Chleb';
SELECT * FROM PRODUKTY 
WHERE STAWKA_PODATKU = 23;*/

SELECT * FROM PRODUKTY 
WHERE STAWKA_PODATKU = (SELECT STAWKA_PODATKU FROM PRODUKTY
                        WHERE NAZWA_PRODUKTU = 'Chleb')
                        AND NAZWA_PRODUKTU <> 'Chleb';
                        
/* ------------------------------------------------------------------------------------------------------------------------------------------------*/
/* £¥CZENIE DOTYCHCZAS POZANYCH INTRUKCJI*/

SELECT P.NAZWA_PRODUKTU, TP.TYP_PRODUKTU, P.CENA_SPRZEDAZY, P.CENA_ZAKUPU, (P.CENA_SPRZEDAZY - P.CENA_ZAKUPU) MARZA, STAWKA_PODATKU FROM PRODUKTY P
JOIN TYPY_PRODUKTÓW TP ON P.TYP_PRODUKTU = TP.TYP_PRODUKTU
WHERE P.CENA_ZAKUPU < 5 OR P.STAWKA_PODATKU > 7;

SELECT TP.NAZWA_PE£NA, ROUND(AVG(P.CENA_SPRZEDAZY - P.CENA_ZAKUPU), 2) AS MARZA,
COUNT(*) ILOŒÆ_PRODUKTÓW
FROM PRODUKTY P
JOIN TYPY_PRODUKTÓW TP ON P.TYP_PRODUKTU = TP.TYP_PRODUKTU
WHERE P.CENA_ZAKUPU < 5 OR P.STAWKA_PODATKU > 7
GROUP BY TP.NAZWA_PE£NA
ORDER BY TP.NAZWA_PE£NA;

SELECT * FROM (SELECT TP.NAZWA_PE£NA, ROUND(AVG(P.CENA_SPRZEDAZY - P.CENA_ZAKUPU), 2) AS MARZA,
COUNT(*) ILOŒÆ_PRODUKTÓW
FROM PRODUKTY P
JOIN TYPY_PRODUKTÓW TP ON P.TYP_PRODUKTU = TP.TYP_PRODUKTU
WHERE P.CENA_ZAKUPU < 5 OR P.STAWKA_PODATKU > 7
GROUP BY TP.NAZWA_PE£NA
ORDER BY TP.NAZWA_PE£NA)
WHERE MARZA > 1;


SELECT ID_PRACOWNICY, IMIE, NAZWISKO, PENSJA 
FROM PRACOWNICY
WHERE PENSJA >= (SELECT PENSJA FROM PRACOWNICY
                 WHERE ID_PRACOWNICY = (SELECT MAX(ID_PRACOWNICY)
                        FROM PRACOWNICY)
                 );
                 
/* ------------------------------------------------------------------------------------------------------------------------------------------------*/
/* DO£¥CZENIE TABEL Z PLIKU*/

@'C:\Users\hsien\OneDrive\Desktop\MYSQL\Kurs YT\departamenty.sql';


UPDATE PRACOWNICY
SET PESEL = 58031245679
WHERE ID_PRACOWNICY=10;

ALTER TABLE PRACOWNICY
MODIFY PESEL VARCHAR2(11);

UPDATE PRACOWNICY 
SET PESEL = NULL;

@'C:\Users\hsien\OneDrive\Desktop\MYSQL\Kurs YT\pracownicy_pesel';

@'';

SELECT * FROM PRACOWNICY;